version: '2'
services:
    outliner-app:
        image: outliner
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://outliner-postgresql:5432/outliner
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=outliner-elasticsearch:9300
        ports:
            - 8080:8080
    outliner-postgresql:
        extends:
            file: postgresql.yml
            service: outliner-postgresql
    outliner-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: outliner-elasticsearch
